package com.pichitube.app.core.network

import kotlinx.serialization.Serializable

@Serializable
data class VideoInfo(
    val videoId: String,
    val title: String,
    val thumbnailUrl: String,
    val channelName: String,
    val channelId: String,
    val channelAvatarUrl: String = "",
    val viewCount: Long = 0L,
    val durationSeconds: Long = 0L,
    val uploadDate: String = "",
    val description: String = "",
    val isShort: Boolean = false,
    val isLive: Boolean = false,
    val likeCount: Long = 0L,
    val dislikeCount: Long = 0L,
    val subscriberCount: Long = 0L,
)

@Serializable
data class StreamInfo(
    val videoId: String,
    val title: String,
    val channelName: String,
    val channelId: String,
    val channelAvatarUrl: String = "",
    val description: String = "",
    val videoStreams: List<VideoStream> = emptyList(),
    val audioStreams: List<AudioStream> = emptyList(),
    val hlsUrl: String? = null,
    val dashManifestUrl: String? = null,
    val thumbnailUrl: String = "",
    val durationSeconds: Long = 0L,
    val viewCount: Long = 0L,
    val likeCount: Long = 0L,
    val uploadDate: String = "",
    val subscriberCount: Long = 0L,
    val subtitles: List<SubtitleTrack> = emptyList(),
    val relatedVideos: List<VideoInfo> = emptyList(),
    val chapters: List<Chapter> = emptyList(),
)

@Serializable
data class VideoStream(
    val url: String,
    val quality: String,
    val format: String,
    val itag: Int = 0,
    val fps: Int = 30,
    val isVideoOnly: Boolean = false,
)

@Serializable
data class AudioStream(
    val url: String,
    val quality: String,
    val format: String,
    val averageBitrate: Int = 0,
    val languageCode: String = "",
    val languageName: String = "Original",
)

@Serializable
data class SubtitleTrack(
    val url: String,
    val languageCode: String,
    val languageName: String,
    val isAutoGenerated: Boolean = false,
) {
    val name: String get() = languageName
    val code: String get() = languageCode
}

typealias Subtitle = SubtitleTrack


@Serializable
data class Chapter(
    val title: String,
    val startTimeSeconds: Long,
    val thumbnailUrl: String = "",
)

@Serializable
sealed class SearchResultItem {
    @Serializable
    data class VideoItem(val video: VideoInfo) : SearchResultItem()

    @Serializable
    data class ChannelItem(
        val channelId: String,
        val title: String,
        val avatarUrl: String = "",
        val subscriberCount: Long = 0L,
        val videoCount: Long = 0L,
        val description: String = "",
    ) : SearchResultItem()

    @Serializable
    data class PlaylistItem(
        val playlistId: String,
        val title: String,
        val thumbnailUrl: String = "",
        val uploaderName: String = "",
        val videoCount: Long = 0L,
    ) : SearchResultItem()
}

@Serializable
data class SearchResult(
    val results: List<VideoInfo> = emptyList(),
    val items: List<SearchResultItem> = emptyList(),
    val nextPageToken: String? = null,
)

@Serializable
data class ChannelInfo(
    val channelId: String,
    val name: String,
    val avatarUrl: String = "",
    val bannerUrl: String = "",
    val description: String = "",
    val subscriberCount: Long = 0L,
    val videos: List<VideoInfo> = emptyList(),
)

fun String.extractResolutionInt(): Int {
    val lower = this.lowercase()
    if (lower.contains("4k") || lower.contains("2160")) return 2160
    if (lower.contains("2k") || lower.contains("1440")) return 1440
    return Regex("(\\d+)p").find(this)?.groupValues?.get(1)?.toIntOrNull() ?: 0
}

